networks:
  moodle: {}
services:
  db:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb_file_per_table=On
      --innodb_large_prefix=On
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: moodle
    image: mysql:5
    networks:
      moodle: {}
  exttests:
    image: moodlehq/moodle-exttests
    networks:
      moodle: {}
  mailhog:
    image: mailhog/mailhog
    networks:
      moodle: {}
  moodle:
    build:
      args:
        PHP_VERSION: '7.2'
      context: /home/terry/workspace/uth/restructure/LMS_Developer_Terry
      dockerfile: .containers/moodle/dockerfile
      target: test
    depends_on:
      db:
        condition: service_started
    environment:
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPASS: moodle
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_WEB_PORT: 127.0.0.1:80
      PHP_IDE_CONFIG: serverName=localhost
      PHP_INI_POST_MAX_SIZE: 1G
      PHP_INI_UPLOAD_MAX_FILESIZE: 1G
      PHP_INI_XDEBUG__REMOTE_AUTOSTART: 1
      TZ: America/Chicago
      XDEBUG_CONFIG: remote_host=localhost
    networks:
      behat:
        aliases:
        - behat
    user: docker
    volumes:
    - /home/terry/workspace/uth/restructure/LMS_Developer_Terry/LMSTools:/app/LMSTools:r0
    - /home/terry/workspace/uth/restructure/LMS_Developer_Terry/test_runs:/app/test_runs:rw
    working_dir: /app
  selenium:
    image: selenium/standalone-firefox:2.53.1
    networks:
      moodle: {}
    shm_size: 2gb
    volumes:
    - /home/terry/workspace/uth/restructure/LMS_Developer_Terry:/app:ro
version: '3.8'

