version: '3.8'
services:

  moodle:
    build:
      dockerfile: .containers/moodle/dockerfile
      context: .
      target: "dev"
    volumes:
      - .:/app:rw
      - ./.containers/moodle/config.php:/app/lms/moodle/config.php:rw
      - ./.containers/moodle/mailhog.conf:/etc/apache2/conf-enabled/mailhog.conf:rw
      - moodledata:/appdata/moodledata
      # - ./.containers/webserver/PwshProfile.ps1:/home/docker/.config/powershell/profile.ps1
    user: docker
    ports:
      - 8080:80

  db:
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3380:3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  selenium:
    # ports:
    #   - 7900:7900

volumes:
  moodledata:
  mysqldata: