version: '3.8'
services:

  moodle:
    build:
      dockerfile: .containers/moodle/dockerfile
      context: .
      target: "dev"
    volumes:
      - .:/app:rw
      # - ./.lmsproject.container.json:/app/.lmsproject.json
      - ./.containers/moodle/config.php:/app/lms/moodle/config.php:rw
      # - ./.containers/moodle/mailhog.conf:/etc/apache2/conf-enabled/mailhog.conf:rw
      # - ./.containers/webserver/PwshProfile.ps1:/home/docker/.config/powershell/profile.ps1
    # user: docker
    ports:
      - 8000:80
    #   - 22:22

  db:
    ports:
      - 3308:3306

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 8025:8025

  selenium:
    ports:
      - 5900:5900
      - 4400:4400
      - 7900:7900