version: '3.8'
services:

  moodle:
    build:
      dockerfile: .containers/moodle/dockerfile
      context: .
      target: "test"
    volumes: ["/home/terry/.local/share/powershell/Modules/LMSTools:/app/LMSTools"]
    ports: []

  db:
    ports: []

  selenium:
    ports: []

