version: '3.8'
services:
  moodle:
    depends_on:
      - db
      # - mailhog
    build:
      dockerfile: .containers/moodle/dockerfile
      context: .
      target: "test"
      args:
        PHP_VERSION: 7.2
    environment:
      TZ: America/Chicago
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPASS: moodle
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_WEB_PORT: 127.0.0.1:80
      PHP_IDE_CONFIG: serverName=localhost
      PHP_INI_UPLOAD_MAX_FILESIZE: 1G
      PHP_INI_POST_MAX_SIZE: 1G
      PHP_INI_XDEBUG__REMOTE_AUTOSTART: 1
      XDEBUG_CONFIG: remote_host=localhost
    networks:
      moodle:
        aliases:
          - behat
    volumes:
      # - .:/app:rw
      - ./LMSTools:/app/LMSTools
      - ./.containers/moodle/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:rw
      # - ./.containers/webserver/apache/mailhog.conf:/etc/apache2/conf-enabled/mailhog.conf:rw
      # - ./.containers/webserver/moodle/config.php:/app/lms/moodle/config.php:rw
      # - ./.containers/webserver/PwshProfile.ps1:/home/docker/.config/powershell/profile.ps1
      # - moodledata:/appdata/moodledata
    working_dir: /app

  db:
    networks:
      moodle:
    image: mysql:5
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      --innodb_file_per_table=On --innodb_large_prefix=On'
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    # volumes:
    #   - mysqldata:/var/lib/mysql

  exttests:
    image: moodlehq/moodle-exttests
    networks:
      moodle:

  mailhog:
    image: mailhog/mailhog
    networks:
      moodle:

  selenium:
    image: selenium/standalone-firefox-debug:2.53.1
    volumes:
      - .:/app:ro
    shm_size: '2gb'
    networks:
      moodle:


networks:
  moodle:
# volumes:
#   moodledata:
#   mysqldata: