version: '3.8'
services:
  webserver:
    depends_on:
      - db
      - mailhog
    build:
      context: .containers/webserver
      args:
        PHP_VERSION: 7.2
    environment:
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPASS: moodle
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_WEB_PORT: 127.0.0.1:8000
      PHP_IDE_CONFIG: serverName=localhost
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
    ports:
      - 127.0.0.1:8000:80/tcp
    volumes:
      - .:/app:rw
      - ./.containers/webserver/apache/000-default.conf:/etc/apache2/conf-enabled/000-default.conf:rw
      - ./.containers/webserver/apache/mailhog.conf:/etc/apache2/conf-enabled/mailhog.conf:rw
      - ./.containers/webserver/moodle/config.php:/app/lms/moodle/config.php:rw
      - ./.containers/webserver/PwshProfile.ps1:/home/docker/.config/powershell/profile.ps1
      - moodledata:/appdata/moodledata
    working_dir: /app

  db:
    image: mysql:5
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb_file_format=barracuda
      --innodb_file_per_table=On --innodb_large_prefix=On'
    ports:
      - 3307:3306/tcp
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - mysqldata:/var/lib/mysql

  exttests:
    image: moodlehq/moodle-exttests

  mailhog:
    image: mailhog/mailhog
    ports:
    - 8025:8025

  selenium:
    image: selenium/standalone-firefox:2.53.1
    volumes:
      - .:/app:ro

volumes:
  moodledata:
  mysqldata: