version: '3.8'

services:

  moodle:
    depends_on:
      - db
    build:
      dockerfile: .containers/moodle/dockerfile
      context: .
      target: "test"
      args:
        PHP_VERSION: 7.2
    environment:
      TZ: America/Chicago
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPASS: moodle
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_WEB_PORT: 8000
      PHP_IDE_CONFIG: serverName=localhost
      PHP_INI_UPLOAD_MAX_FILESIZE: 1G
      PHP_INI_POST_MAX_SIZE: 1G
      # PHP_INI_XDEBUG__REMOTE_AUTOSTART: 1
#      PHP_INI_XDEBUG__REMOTE_HOST: localhost
#      XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST} remote_autostart=On"
      # XDEBUG_CONFIG: remote_host=localhost
    user: docker
    ports:
      - 80
      - 22
    networks:
      moodle:
        aliases:
          - behat
    tmpfs:
      - /appdata
    volumes:
      # - .:/app:rw
      # - ./LMSTools:/app/LMSTools
      - ./test_runs:/app/test_runs
      # - ./.containers/moodle/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:rw
      # - ./.containers/webserver/apache/mailhog.conf:/etc/apache2/conf-enabled/mailhog.conf:rw
      # - ./.containers/webserver/moodle/config.php:/app/lms/moodle/config.php:rw
      # - ./.containers/webserver/PwshProfile.ps1:/home/docker/.config/powershell/profile.ps1
      # - moodledata:/appdata/moodledata
    working_dir: /app

  db:
    networks:
      moodle:
    ports:
      - 3306
    image: mysql:5
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      --innodb_file_per_table=On --innodb_large_prefix=On'
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    tmpfs:
      - /var/lib/mysql

  selenium:
    # image: selenium/standalone-firefox-debug:2.53.1
    image: selenium/standalone-firefox-debug:2.53.1
    volumes:
      - .:/app:ro
    shm_size: '2gb'
    networks:
      moodle:

networks:
  moodle: