ARG PHP_VERSION=7.2

FROM php:7.2-apache-buster AS base

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync \
    && install-php-extensions gd xmlrpc mysqli intl zip \
    && apt-get update && apt-get install -y sudo git wget locales locales-all \
    && update-locale en_AU.UTF8

    # Install Powershell
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y powershell


RUN useradd -ms /bin/bash docker && adduser docker sudo
# Users in the sudoers group can sudo as root without password.
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY ./.containers/moodle/PwshProfile.ps1 /home/docker/.config/powershell/profile.ps1

# COPY phpunit.sh /usr/local/bin/phpunit.sh
# RUN chmod +x /usr/local/bin/phpunit.sh
# ENTRYPOINT /usr/local/bin/phpunit.sh

# COPY ./.containers/moodle/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./.containers/moodle/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

RUN sudo mkdir -p /appdata/behatdata
RUN sudo mkdir /appdata/moodledata
RUN sudo mkdir /appdata/phpunitdata
RUN sudo chown -R docker:docker /appdata

USER docker

RUN pwsh -command "install-module powershell-yaml -Scope CurrentUser -force"

# ---TEST ---
FROM base AS Test
COPY --chown=docker:docker ./lms /app/lms
COPY --chown=docker:docker  ./.containers/moodle/config.php /app/lms/moodle/config.php
COPY --chown=docker:docker  ./tests /app/tests
# COPY ./LMSTools_New /app/LMSTools
COPY --chown=docker:docker  ./.lmsproject.json /app/
COPY --chown=docker:docker  ./components.csv /app/


# --- DEV ---
FROM base AS Dev
USER root
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request = yes"  >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host = localhost" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini